### ISSUE TITLE
Cant install on atom 1.8

### ISSUE THREAD

**Issue by jcbritobr** [frairon/go-outline#42]
Go outline fail to install on atom 1.8 in windows 10
Here is the trace :

> runas@3.1.1 install C:\Users\jgardona\AppData\Local\Temp\apm-install-dir-116524-11344-3rpg0y\node_modules\go-outline\node_modules\pathwatcher\node_modules\runas
> node-gyp rebuild

C:\Users\jgardona\AppData\Local\Temp\apm-install-dir-116524-11344-3rpg0y\node_modules\go-outline\node_modules\pathwatcher\node_modules\runas>if not defined npm_config_node_gyp (node "C:\Users\jgardona\AppData\Local\atom\app-1.8.0\resources\app\apm\node_modules\npm\bin\node-gyp-bin\....\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild ) 

gypnpm ERR! Windows_NT 6.2.9200
npm ERR! argv "C:\Users\jgardona\AppData\Local\atom\app-1.8.0\resources\app\apm\bin\node.exe" "C:\Users\jgardona\AppData\Local\atom\app-1.8.0\resources\app\apm\node_modules\npm\bin\npm-cli.js" "--globalconfig" "C:\Users\jgardona\.atom\.apm\.apmrc" "--userconfig" "C:\Users\jgardona\.atom\.apmrc" "install" "C:\Users\jgardona\AppData\Local\Temp\d-116524-11344-l22mi3\package.tgz" "--target=0.36.8" "--arch=ia32"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! runas@3.1.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the runas@3.1.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the runas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls runas
npm ERR! There is likely additional logging output above.

**Comment by lkarlslund** [comment]
Same thing here. Tried 0.2.1 and 0.4.0 versions on numerous versions of Atom. This package haven't worked even once on my Windows setup :-(

> runas@3.1.1 install C:\Users\LAK\AppData\Local\Temp\apm-install-dir-11666-14528-1xr1fas\node_modules\go-outline\node_modules\pathwatcher\node_modules\runas
> node-gyp rebuild

C:\Users\LAK\AppData\Local\Temp\apm-install-dir-11666-14528-1xr1fas\node_modules\go-outline\node_modules\pathwatcher\node_modules\runas>if not defined npm_config_node_gyp (node "C:\Users\LAK\AppData\Local\atom\app-1.8.0\resources\app\apm\node_modules\npm\bin\node-gyp-bin\....\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild ) 

gypnpm ERR! Windows_NT 6.2.9200
npm ERR! argv "C:\Users\LAK\AppData\Local\atom\app-1.8.0\resources\app\apm\bin\node.exe" "C:\Users\LAK\AppData\Local\atom\app-1.8.0\resources\app\apm\node_modules\npm\bin\npm-cli.js" "--globalconfig" "C:\Users\LAK\.atom\.apm\.apmrc" "--userconfig" "C:\Users\LAK\.atom\.apmrc" "install" "C:\Users\LAK\AppData\Local\Temp\d-11666-14528-u6t4g0\package.tgz" "--target=0.36.8" "--arch=ia32"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! runas@3.1.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the runas@3.1.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the runas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls runas
npm ERR! There is likely additional logging output above.

Please fix - would very much like to use it!

**Comment by frairon** [comment]
Sorry guys, I admit it... I never tried that on another architecture than Linux but now it seems necessary.
Give me some time, I'll try to get that running as soon as possible.

**Comment by lkarlslund** [comment]
I uninstalled Python 2.7, and reinstalled it as 32-bit (on my 64-bit system).

Now it installs fine. But very cryptic message, and troubleshooting was by guessing :(

**Comment by frairon** [comment]
Well.. for another issue I changed the d3-version (which was automatically updated to 4.0 but unfortunately d3 has changed a bit from 4.0). Maybe that did the trick for you too. I'm not sure what Python has to do with all that... Once I get a windows box up and running, I'll try.

**Comment by typhoonzero** [comment]
same issue on mac: 

```
Installing “go-outline@0.4.1” failed.Hide output…

> runas@3.1.1 install /private/var/folders/qc/73bf7wq16d974w4y44w22b1w0000gn/T/apm-install-dir-11678-8003-726vwo/node_modules/go-outline/node_modules/pathwatcher/node_modules/runas
> node-gyp rebuild

  CXX(target) Release/obj.target/runas/src/main.o
  CXX(target) Release/obj.target/runas/src/runas_darwin.o
  CXX(target) Release/obj.target/runas/src/fork.o
  SOLINK_MODULE(target) Release/runas.node

ld: library not found for -lgcc_s.10.5
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Release/runas.node] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Darwin 15.6.0
gyp ERR! command "node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /private/var/folders/qc/73bf7wq16d974w4y44w22b1w0000gn/T/apm-install-dir-11678-8003-726vwo/node_modules/go-outline/node_modules/pathwatcher/node_modules/runas
gyp ERR! node -v v0.10.40
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 
npm ERR! Darwin 15.6.0
npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/wuyi/.atom/.apm/.apmrc" "--userconfig" "/Users/wuyi/.atom/.apmrc" "install" "/private/var/folders/qc/73bf7wq16d974w4y44w22b1w0000gn/T/d-11678-8003-1mxy3e3/package.tgz" "--target=0.37.8" "--arch=x64"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! runas@3.1.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the runas@3.1.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the runas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls runas
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/qc/73bf7wq16d974w4y44w22b1w0000gn/T/apm-instal
```

**Comment by ghost** [comment]
Can't install (Atom1.18.0 x64, Windows10). 

Installing “go-outline@0.6.6” failed.

> runas@3.1.1 install C:\Users\agrin\AppData\Local\Temp\apm-install-dir-117517-4764-tvzjjk.ui0o7ds4i\node_modules\go-outline\node_modules\runas
> node-gyp rebuild


C:\Users\agrin\AppData\Local\Temp\apm-install-dir-117517-4764-tvzjjk.ui0o7ds4i\node_modules\go-outline\node_modules\runas>if not defined npm_config_node_gyp (node "C:\Users\agrin\AppData\Local\atom\app-1.18.0\resources\app\apm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\agrin\AppData\Local\atom\app-1.18.0\resources\app\apm\bin\\..\node_modules\node-gyp\bin\node-gyp.js" rebuild ) 
C:\Users\agrin\AppData\Local\Temp\apm-install-dir-117517-4764-tvzjjk.ui0o7ds4i
`-- (empty)


gyp ERR! configure error 
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (C:\Users\agrin\AppData\Local\atom\app-1.18.0\resources\app\apm\node_modules\node-gyp\lib\configure.js:449:14)
gyp ERR! stack     at C:\Users\agrin\AppData\Local\atom\app-1.18.0\resources\app\apm\node_modules\node-gyp\lib\configure.js:404:11
gyp ERR! stack     at C:\Users\agrin\AppData\Local\atom\app-1.18.0\resources\app\apm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:123:15)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "C:\\Users\\agrin\\AppData\\Local\\atom\\app-1.18.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\agrin\\AppData\\Local\\atom\\app-1.18.0\\resources\\app\\apm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\agrin\AppData\Local\Temp\apm-install-dir-117517-4764-tvzjjk.ui0o7ds4i\node_modules\go-outline\node_modules\runas
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\agrin\AppData\Local\Temp\apm-install-dir-117517-4764-tvzjjk.ui0o7ds4i\package.json'
npm WARN apm-install-dir-117517-4764-tvzjjk.ui0o7ds4i No description
npm WARN apm-install-dir-117517-4764-tvzjjk.ui0o7ds4i No repository field.
npm WARN apm-install-dir-117517-4764-tvzjjk.ui0o7ds4i No README data
npm WARN apm-install-dir-117517-4764-tvzjjk.ui0o7ds4i No license field.
npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Users\\agrin\\AppData\\Local\\atom\\app-1.18.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\agrin\\AppData\\Local\\atom\\app-1.18.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\agrin\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\agrin\\.atom\\.apmrc" "install" "C:\\Users\\agrin\\AppData\\Local\\Temp\\d-117517-4764-irqg0r.lon7hnnrk9\\package.tgz" "--runtime=electron" "--target=1.3.15" "--arch=x64" "--global-style"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! runas@3.1.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the runas@3.1.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the runas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs runas
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls runas
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\agrin\AppData\Local\Temp\apm-install-dir-117517-4764-tvzjjk.ui0o7ds4i\npm-debug.log
npm ERR! code 1

**Comment by frairon** [comment]
Removed pathwatcher dependency, maybe it's related to that. Reopen if there's still an issue
