### ISSUE TITLE
No live updates

### ISSUE THREAD

**Issue by simongui** [frairon/go-outline#46]
I'm running this on Atom 1.8 and I see the outline but it's not updating when I make changes and save the file.

Also would it be possible to install the dependencies go-outline requires in the vendor directory like how `go-plus` does? This way the dependency doesn't get put where my project source code is located in src.

**Comment by frairon** [comment]
hi simongui, 
for the first issue: are you sure the file not being updated was correct go-code? When the code has syntax errors, the parsing fails and the tree is not updated. when issue #37 is fixed, there will be at least a notification of something being failed.. 
If you can be sure your code is correct, it would be nice to know how to reproduce that error.

The dependency-issue is a good idea, I'll look into that, thanks!

Cheers

**Comment by pokstad** [comment]
I'm having the same problem with the latest version of Atom (1.12.4) on macOS. The outline only updates when initially enabled. I experimented adding a simple package level variable to see if it would update and no luck.

**Comment by telemmaite** [comment]
Same here not updating with Atom 1.12.7

**Comment by frairon** [comment]
I'll close the issue, it's way too old.
