### ISSUE TITLE
helpers.coffee bad regex for windows

### ISSUE THREAD

**Issue by telemmaite** [frairon/go-outline#52]
https://github.com/frairon/go-outline/blob/master/lib/helpers.coffee#L8
Give windows some love the regex here need to be changed.
It clears everything for a path such as 

> E:\GO_WP\src\github.com\telemmaite\hello\hello.go

https://regex101.com/r/oYTpLH/1

In my case it worked right away after I changed it to 
```
  dirname: (path) ->
    return path.replace(/[^\/\\]+$/, '')

**Comment by frairon** [comment]
Resolved by tro3, thanks a lot!
