### ISSUE TITLE
Remove mouse-up behaviour

### ISSUE THREAD

**Issue by miketonks** [frairon/go-outline#53]
When selecting a block of code in the editor, very often the mouse goes over the go-outline panel.  When releasing mouse e.g. to end selection, if it's over the go outline-view panel then this jumps to a different part of my file, i.e. where the function definition lives.

Obviously 'click' event should do this, but I don't think 'mouse-up' behaviour is correct.

Really love the go-outline view btw.  Amazing!

**Comment by frairon** [comment]
Nice! Thanks for reporting that. I haven't had the issue yet, but it sounds like a really small fix, so I'll look into it the next days.

**Comment by frairon** [comment]
done (v0.6.2)

**Comment by miketonks** [comment]
Installed github version and confirmed fix.  Thanks!
