### ISSUE TITLE
Deprecated selector in `go-outline/styles/go-outline.less`

### ISSUE THREAD

**Issue by elemc** [frairon/go-outline#56]
In `go-outline/styles/go-outline.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `atom-text-editor::shadow .line.go-outline-highlight-line` => `atom-text-editor.editor .line.go-outline-highlight-line`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by frairon** [comment]
resolved in 0.6.6, thanks a lot!

**Comment by elemc** [comment]
Thanks.
